ALTER SESSION SET "_ORACLE_SCRIPT"=true;

--
-- Users
--

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER LPORTAL IDENTIFIED BY 1234 DEFAULT TABLESPACE USERS;
GRANT CREATE CLUSTER TO "LPORTAL";
GRANT CREATE DATABASE LINK TO "LPORTAL" ;
GRANT CREATE SESSION TO "LPORTAL" ;
GRANT CREATE TRIGGER TO "LPORTAL" ;
GRANT CREATE ANY TRIGGER TO "LPORTAL" ;
GRANT UNLIMITED TABLESPACE TO "LPORTAL" ;
GRANT CREATE ANY LIBRARY TO "LPORTAL" ;
GRANT CREATE SYNONYM TO "LPORTAL" ;
GRANT CREATE SEQUENCE TO "LPORTAL" ;
GRANT CREATE SNAPSHOT TO "LPORTAL" ;
GRANT CREATE TABLE TO "LPORTAL" ;
GRANT CREATE VIEW TO "LPORTAL" ;
GRANT SELECT ANY TABLE TO "LPORTAL" ;
GRANT CREATE TYPE TO "LPORTAL" ;
GRANT CREATE LIBRARY TO "LPORTAL" ;
GRANT CREATE DIMENSION TO "LPORTAL" ;
GRANT CREATE OPERATOR TO "LPORTAL" ;
GRANT CREATE INDEXTYPE TO "LPORTAL" ;
GRANT IMP_FULL_DATABASE TO "LPORTAL" ;
GRANT IMPORT FULL DATABASE TO "LPORTAL" ;
GRANT CONNECT TO "LPORTAL";
COMMIT;

